Build tests separately and download into container

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -19,10 +19,78 @@ env:
   TSFFS_SIMICS_PKG_VERSION: "6.0.0"
 
 jobs:
+  build_test_artifacts:
+    name: Build Test Artifacts
+    runs-on: ubuntu-latest
+    steps:
+      - name: Add ISPM to PATH
+        run: |
+          echo "${HOME}/simics/ispm/" >> "${GITHUB_PATH}"
+
+      - name: Install Dependencies
+        run: |
+          apt-get -y update && \
+          apt-get -y install \
+            clang libclang-dev cmake curl dosfstools g++ gcc git llvm make \
+            mtools ninja-build openssl libssl-dev python3 python3-pip
+
+      - name: Cache SIMICS Dependencies
+        id: cache-simics-packages
+        uses: actions/cache@v3
+        with:
+          path: ~/simics
+          key: simics-linux-${{ env.PUBLIC_SIMICS_PACKAGE_VERSION_1000 }}
+
+      - name: Install SIMICS (External)
+        if: ${{ steps.cache-simics-packages.outputs.cache-hit != 'true' }}
+        run: |
+          mkdir -p "${HOME}/simics/ispm/" && \
+          curl --noproxy -L -o "${HOME}/simics/ispm.tar.gz" \
+              "${{ env.PUBLIC_SIMICS_ISPM_URL }}" && \
+          curl --noproxy -L -o "${HOME}/simics/simics.ispm" \
+              "${{ env.PUBLIC_SIMICS_PKGS_URL }}" && \
+          tar -C "${HOME}/simics/ispm" --strip-components=1 \
+              -xvf "${HOME}/simics/ispm.tar.gz"
+
+      - name: Set up SIMICS Install Directory
+        run: |
+          ispm settings install-dir "${HOME}/simics"
+
+      - name: Install SIMICS Packages
+        if: ${{ steps.cache-simics-packages.outputs.cache-hit != 'true' }}
+        run: |
+          ispm packages --install-bundle "${HOME}/simics/simics.ispm" \
+              --non-interactive --trust-insecure-packages
+
+      - uses: actions/checkout@v4
+        with:
+          lfs: true
+
+      - name: Cache Test Artifacts
+        id: cache-test-artifacts
+        uses: actions/cache@v3
+        with:
+          path: examples/tests
+          key: cache-test-artifacts-${{ hashFiles('examples/tests/**/*') }}
+
+      - name: Build Test Artifacts
+        run: |
+          cd examples/tests/
+          ./build.sh
+
+      - name: Upload Test Artifacts
+        if: ${{ steps.cache-test-artifacts.outputs.cache-hit != 'true' }}
+        uses: actions/upload-artifact@v3
+        with:
+          name: test-artifacts
+          path: examples/tests/
+
+
   build_and_test:
     name: Build and Test (Linux)
     container: fedora:38
     runs-on: ubuntu-latest
+    needs: build_test_artifacts
     steps:
       - name: Add ISPM to PATH
         run: |
@@ -42,6 +110,16 @@ jobs:
       - uses: actions/checkout@v4
         with:
           lfs: true
+
+      - name: Delete Un-Built Test Dependencies
+        run: |
+          rm -rf examples/tests/
+
+      - name: Download Test Dependencies
+        uses: actions/download-artifact@v3
+        with:
+          name: test-artifacts
+          path: examples/tests/
 
       - uses: dtolnay/rust-toolchain@nightly
         with:
@@ -98,7 +176,7 @@ jobs:
 
       - name: Test Project
         run: |
-          SIMICS_BASE=${HOME}/simics/simics-${{ env.PUBLIC_SIMICS_PACKAGE_VERSION_1000 }} cargo test -p command-ext -p raw-cstr -p tmp-dir -p version-tools || ( echo "❗ Tests failed" && exit 1 )
+          SIMICS_BASE=${HOME}/simics/simics-${{ env.PUBLIC_SIMICS_PACKAGE_VERSION_1000 }} cargo test -p command-ext -p raw-cstr -p tmp-dir -p version-tools -p tests || ( echo "❗ Tests failed" && exit 1 )
           echo "✅ Tests passed"
 
       - name: Build Docs
